/*
 Dimension Exploration
*/

-- Explore all countries our customers from table

select distinct country from gold_dim_customers;

-- Explore all categories "the major divisions"

select distinct category,subcategory,product_name from gold_dim_products;


/*
 Date Exploration
*/
-- find the date of the first and last order

select 
min(order_date) as first_order_date,
max(order_date) as last_order_date,
timestampdiff(month,min(order_date), max(order_date)) as order_range_months
from gold_fact_sales;

-- find the youngest and the oldest customer

select 
min(birthdate) as oldest_birthdate,
max(birthdate) as youngest_birthdate,
timestampdiff(month,min(birthdate), CURDATE()) as oldest_age,
timestampdiff(month,max(birthdate),CURDATE()) as youngest_age
from gold_dim_customers;

/*
 Measures Exploration
*/

-- Find the total sales
select sum(sales_amount) as total_Sales 
from gold_fact_sales;

-- FInd how many items are sold

select sum(quantity) as Total_quantity 
from gold_fact_sales;

-- Find the average selling price

Select avg(price) as avg_price from gold_fact_sales;


-- FInd the total number of orders

select count(order_number) as total_orders 
from gold_fact_sales;

select count(distinct order_number) as total_orders from  gold_fact_sales;

-- FInd the total number of products

select count(product_name) as total_products 
from gold_dim_products;

select count(distinct product_name) as total_products from  gold_dim_products;

-- Find the total number of customers

select count(customer_key) as total_customers from gold_fact_sales;

-- Find the total number of customers that has placed an order

select count(distinct customer_key) as total_customers from gold_fact_sales;

-- Generate a report that shows all the key metrics of the business

select 'Total Sales' as measure_name, sum(sales_amount) as measure_value from gold_fact_sales
union all
select 'Total_quantity' ,sum(quantity)  from gold_fact_sales
union all
select 'Total_orders',count(distinct order_number) as total_orders from gold_fact_sales
union all
select 'total_products' ,count(distinct product_name)  from gold_dim_products
union all
select 'Total_customers' ,count(distinct customer_key)  from gold_fact_sales;

-- Magnitude Analysis

-- Find total customers by countries

select country,count(customer_key) as total_customers
from gold_dim_customers
group by country
order by total_customers DESC;

-- Find total customers by gender

select gender,count(customer_key) as total_customers
from gold_dim_customers
group by gender
order by total_customers DESC;

-- Find total products by category
select category,
count(product_key) as total_products
from gold_dim_products
group by category
order by total_products DESC;

-- What is the average costs in each category?

select category,
avg(cost) as avg_costs
from gold_dim_products
group by category
order by avg_costs DESC;


-- What is the total revenue generated for each category?

select 
p.category,
sum(f.sales_amount) as total_revenue
 from gold_fact_sales f
left join gold_dim_products p 
on p.product_key = f.product_key
group by p.category
order by total_revenue DESC;

-- Find total revenue is generated by each customer
select
c.customer_key,
c.first_name,
c.last_name,
sum(f.sales_amount) as total_revenue
from gold_fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by c.customer_key,
c.first_name,
c.last_name
order by total_revenue DESC;

-- What is the distribution of sold items across countries?

select c.country,
sum(f.quantity)  as total_sold_items
from gold_fact_sales f
left join gold_dim_customers c
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items DESC;


/*
 Ranking Analysis
*/

-- WHich 5 products generate the highest revenue?
select *
from (
select p.product_name,
sum(f.sales_amount) as total_revenue,
row_number() over(order by sum(f.sales_amount) DESC) as rank_products
from gold_fact_sales f
left join gold_dim_products p
on p.product_key = f.product_key
group by p.product_name
order by total_revenue DESC
) t 
where rank_products<=5;


-- what are the 5 worst performing products in terms of sales?
 
SELECT 
p.product_name,
SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_products p
ON p.product_key = f.product_key
GROUP BY p.product_name
ORDER BY total_revenue
limit 5;

-- FInd the top 10 customers who have generated the highest revenue
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold_fact_sales f
LEFT JOIN gold_dim_customers c
    ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC
limit 10;



-- The 3 customers with the fewst orders placed

SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    COUNT(DISTINCT order_number) AS total_orders
FROM
    gold_fact_sales f
        LEFT JOIN
    gold_dim_customers c ON c.customer_key = f.customer_key
GROUP BY c.customer_key , c.first_name , c.last_name
ORDER BY total_orders DESC
LIMIT 10;


